// Generated by cargo run --bin export-contracts --locked. Do not edit.
export type CustomerMessage = { message: string, assessor: AssessorId, };
export type AssessorId = "code" | "jev" | "llm";
export type AssessorOption = { id: AssessorId, label: string, available: boolean, unavailable_reason: string | null, };
export type Intent = "claim" | "policy_change" | "customer_details" | "billing";
export type RunState = "assessing" | "clarification_required" | "review_required" | "failed";
export type TaskState = "review_required";
export type ServicingTask = { intent: Intent, state: TaskState, };
export type CustomerReply = { run_id: string, state: RunState, reply: string, tasks: Array<ServicingTask>, execution_trace: Array<ExecutionTraceEvent>, };
export type ApiError = { code: string, message: string, run_id: string | null, };
export type IntentSignal = { intent: Intent, probability: number | null, matched: boolean, };
export type ExecutionTraceEvent = { stage: string, outcome: string, elapsed_ms: number | null, };
export type ProviderExchange = { request_body: string, response_status: number | null, response_body: string | null, response_truncated: boolean, };
export type OperatorRun = { run_id: string, state: RunState, assessor: string, model: string | null, rubric_version: string, routing_version: string, elapsed_ms: number | null, input_tokens: number | null, output_tokens: number | null, signals: Array<IntentSignal>, tasks: Array<ServicingTask>, failure_code: string | null, };
export type OperatorRunDetail = { run: OperatorRun, provider_exchange: ProviderExchange | null, execution_trace: Array<ExecutionTraceEvent>, };
