// Generated by cargo run --bin export-contracts --locked. Do not edit.
export type CustomerMessage = { message: string, assessor: AssessorId, };
export type AssessorId = "code" | "jev" | "llm";
export type AssessorOption = { id: AssessorId, label: string, available: boolean, unavailable_reason: string | null, };
export type Intent = "claim" | "policy_change" | "customer_details" | "billing";
export type RunState = "assessing" | "clarification_required" | "review_required" | "failed";
export type TaskState = "review_required";
export type ServicingTask = { intent: Intent, state: TaskState, };
export type CustomerReply = { run_id: string, state: RunState, reply: string, tasks: Array<ServicingTask>, execution_trace: Array<ExecutionTraceEvent>, };
export type ApiError = { code: string, message: string, run_id: string | null, };
export type IntentSignal = { intent: Intent, probability: number | null, matched: boolean, };
export type ExecutionTraceEvent = { stage: string, outcome: string, elapsed_ms: number | null, };
export type ProviderExchange = { request_body: string, response_status: number | null, response_body: string | null, response_truncated: boolean, };
export type OperatorRun = { run_id: string, state: RunState, assessor: string, model: string | null, rubric_version: string, routing_version: string, elapsed_ms: number | null, input_tokens: number | null, output_tokens: number | null, signals: Array<IntentSignal>, tasks: Array<ServicingTask>, failure_code: string | null, };
export type OperatorRunDetail = { run: OperatorRun, provider_exchange: ProviderExchange | null, execution_trace: Array<ExecutionTraceEvent>, };
export type LiveLog = { sequence: number, occurred_at_ms: number, level: string, fields: { [key in string]: string }, };
export type ProviderId = "code" | "jev" | "openai";
export type WorkflowSubmission = { message: string, providers: Array<ProviderId>, client_request_id: string, };
export type RouterId = "openrouter" | "azure_foundry";
export type PlannerChoice = "openai";
export type DecisionChoice = "jev" | "openai_decisions" | "microsoft_decisions";
export type RouterOption = { id: RouterId, label: string, needs_endpoint: boolean, endpoint_hint: string | null, help: string, };
export type PlannerChoiceOption = { id: PlannerChoice, label: string, 
/**
 * Routers that can serve this choice; empty means not yet available.
 */
routers: Array<RouterId>, note: string | null, };
export type DecisionChoiceOption = { id: DecisionChoice, label: string, 
/**
 * Workflow provider slot filled by this choice, once it has an adapter.
 */
provider: ProviderId | null, routers: Array<RouterId>, note: string | null, };
export type ConnectionCatalog = { routers: Array<RouterOption>, planners: Array<PlannerChoiceOption>, decisions: Array<DecisionChoiceOption>, };
export type PlannerRoute = { choice: PlannerChoice, router: RouterId, };
export type DecisionRoute = { choice: DecisionChoice, router: RouterId, };
export type RouterCredential = { router: RouterId, api_key: string, endpoint: string | null, };
export type ConnectionSetup = { planner: PlannerRoute | null, decisions: Array<DecisionRoute>, credentials: Array<RouterCredential>, };
export type CostSource = "reported" | "estimated";
export type WorkflowResume = { run_id: string, expected_plan_id: string, expected_task_id: string, client_request_id: string, message: string, employee_review: boolean, };
export type PlannerOption = { available: boolean, model: string | null, };
export type DecisionProviderOption = { id: ProviderId, available: boolean, model: string | null, capability: string, };
export type WorkflowLimits = { max_tasks: number, max_steps: number, deadline_ms: number, };
export type WorkflowOptions = { planner: PlannerOption, providers: Array<DecisionProviderOption>, limits: WorkflowLimits, synthetic_only: boolean, connections: ConnectionCatalog, };
export type WorkflowState = "running" | "completed" | "clarification" | "employee_review" | "failed" | "interrupted";
export type WorkflowTaskKind = "tool" | "decision";
export type WorkflowTask = { id: string, kind: WorkflowTaskKind, name: string, depends_on: Array<string>, state: string, };
export type WorkflowPlan = { plan_id: string, tasks: Array<WorkflowTask>, };
export type WorkflowEvent = { sequence: number, comparison_id: string, run_id: string, task_id: string | null, provider: ProviderId | null, model: string | null, actor: string, plan_id: string | null, policy_version: string, schema_version: string, stage: string, outcome: string, occurred_at_ms: number, recorded_at_ms: number | null, };
export type WorkflowUsage = { input_tokens: number | null, output_tokens: number | null, attempts: number, 
/**
 * Spend in US dollars; `None` when the route neither reports cost nor has a configured price.
 */
cost_usd: number | null, 
/**
 * Whether `cost_usd` was reported by the router or estimated from tokens and list prices.
 */
cost_source: CostSource | null, };
export type WorkflowRun = { run_id: string, plan_id: string, provider: ProviderId, model: string | null, state: WorkflowState, reply: string, tasks: Array<WorkflowTask>, event_trace: Array<WorkflowEvent>, usage: WorkflowUsage, elapsed_ms: number, failure_code: string | null, };
export type WorkflowComparison = { comparison_id: string, input_key: string, base_plan: WorkflowPlan, runs: Array<WorkflowRun>, mode: string, complete: boolean, planner_model: string | null, planner_usage: WorkflowUsage, failure_code: string | null, };
export type WorkflowDecisionRecord = { run_id: string, plan_id: string, decision_input_key: string, question_id: string, question_version: string, provider: ProviderId, model: string | null, policy_version: string, result: string, confidence_semantics: string | null, usage: WorkflowUsage, elapsed_ms: number, complete: boolean, task_id: string, attempt: number, context_json: string, question_json: string, };
export type OperatorWorkflow = { comparison: WorkflowComparison, message: string, decisions: Array<WorkflowDecisionRecord>, protected_context_json: string, };
