// Generated by cargo run --bin export-contracts --locked. Do not edit.
export type CustomerMessage = { message: string, };
export type Intent = "claim" | "policy_change" | "customer_details" | "billing";
export type RunState = "assessing" | "clarification_required" | "review_required" | "failed";
export type TaskState = "review_required";
export type ServicingTask = { intent: Intent, state: TaskState, };
export type CustomerReply = { run_id: string, state: RunState, reply: string, tasks: Array<ServicingTask>, };
export type ApiError = { code: string, message: string, run_id: string | null, };
export type IntentSignal = { intent: Intent, probability: number | null, matched: boolean, };
export type OperatorRun = { run_id: string, state: RunState, assessor: string, model: string | null, rubric_version: string, routing_version: string, elapsed_ms: number | null, input_tokens: number | null, output_tokens: number | null, signals: Array<IntentSignal>, tasks: Array<ServicingTask>, failure_code: string | null, };
