use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Deserialize, Serialize, TS)]
#[serde(deny_unknown_fields)]
pub struct CustomerMessage {
    pub message: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Deserialize, Serialize, TS)]
#[serde(rename_all = "snake_case")]
pub enum Intent {
    Claim,
    PolicyChange,
    CustomerDetails,
    Billing,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "snake_case")]
pub enum RunState {
    Assessing,
    ClarificationRequired,
    ReviewRequired,
    Failed,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "snake_case")]
pub enum TaskState {
    ReviewRequired,
}

#[derive(Clone, Serialize, TS)]
pub struct ServicingTask {
    pub intent: Intent,
    pub state: TaskState,
}

#[derive(Clone, Serialize, TS)]
pub struct CustomerReply {
    pub run_id: String,
    pub state: RunState,
    pub reply: String,
    pub tasks: Vec<ServicingTask>,
}

#[derive(Clone, Serialize, TS)]
pub struct ApiError {
    pub code: String,
    pub message: String,
    pub run_id: Option<String>,
}

#[derive(Clone, Serialize, TS)]
pub struct IntentSignal {
    pub intent: Intent,
    pub probability: Option<f64>,
    pub matched: bool,
}

#[derive(Clone, Serialize, TS)]
pub struct OperatorRun {
    pub run_id: String,
    pub state: RunState,
    pub assessor: String,
    pub model: Option<String>,
    pub rubric_version: String,
    pub routing_version: String,
    pub elapsed_ms: Option<u32>,
    pub input_tokens: Option<u32>,
    pub output_tokens: Option<u32>,
    pub signals: Vec<IntentSignal>,
    pub tasks: Vec<ServicingTask>,
    pub failure_code: Option<String>,
}

/// Both checked-in browser bindings and contract tests use this single definition.
pub fn typescript() -> String {
    let config = ts_rs::Config::default();
    format!(
        "// Generated by cargo run --bin export-contracts --locked. Do not edit.\n{}\n",
        [
            CustomerMessage::decl(&config),
            Intent::decl(&config),
            RunState::decl(&config),
            TaskState::decl(&config),
            ServicingTask::decl(&config),
            CustomerReply::decl(&config),
            ApiError::decl(&config),
            IntentSignal::decl(&config),
            OperatorRun::decl(&config),
        ]
        .map(|declaration| format!("export {declaration}"))
        .join("\n")
    )
}
