use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(
    Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Deserialize, Serialize, TS,
)]
#[serde(rename_all = "snake_case")]
pub enum AssessorId {
    #[default]
    Code,
    Jev,
    Llm,
}

impl AssessorId {
    pub const ALL: [Self; 3] = [Self::Code, Self::Jev, Self::Llm];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Code => "code",
            Self::Jev => "jev",
            Self::Llm => "llm",
        }
    }
}

#[derive(Deserialize, Serialize, TS)]
#[serde(deny_unknown_fields)]
pub struct CustomerMessage {
    pub message: String,
    #[serde(default)]
    pub assessor: AssessorId,
}

#[derive(Clone, Serialize, TS)]
pub struct AssessorOption {
    pub id: AssessorId,
    pub label: String,
    pub available: bool,
    pub unavailable_reason: Option<String>,
}

pub use crate::domain::Intent;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "snake_case")]
pub enum RunState {
    Assessing,
    ClarificationRequired,
    ReviewRequired,
    Failed,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "snake_case")]
pub enum TaskState {
    ReviewRequired,
}

#[derive(Clone, Serialize, TS)]
pub struct ServicingTask {
    pub intent: Intent,
    pub state: TaskState,
}

#[derive(Clone, Serialize, TS)]
pub struct CustomerReply {
    pub run_id: String,
    pub state: RunState,
    pub reply: String,
    pub tasks: Vec<ServicingTask>,
    pub execution_trace: Vec<ExecutionTraceEvent>,
}

#[derive(Clone, Serialize, TS)]
pub struct ApiError {
    pub code: String,
    pub message: String,
    pub run_id: Option<String>,
}

#[derive(Clone, Serialize, TS)]
pub struct IntentSignal {
    pub intent: Intent,
    pub probability: Option<f64>,
    pub matched: bool,
}

#[derive(Clone, Serialize, TS)]
pub struct ExecutionTraceEvent {
    pub stage: String,
    pub outcome: String,
    pub elapsed_ms: Option<u32>,
}

#[derive(Clone, Serialize, TS)]
pub struct OperatorRun {
    pub run_id: String,
    pub state: RunState,
    pub assessor: String,
    pub model: Option<String>,
    pub rubric_version: String,
    pub routing_version: String,
    pub elapsed_ms: Option<u32>,
    pub input_tokens: Option<u32>,
    pub output_tokens: Option<u32>,
    pub signals: Vec<IntentSignal>,
    pub tasks: Vec<ServicingTask>,
    pub failure_code: Option<String>,
    #[serde(skip_serializing)]
    #[ts(skip)]
    pub provider_exchange: Option<crate::assessment::ProviderExchange>,
    #[serde(skip_serializing)]
    #[ts(skip)]
    pub execution_trace: Vec<ExecutionTraceEvent>,
}

#[derive(Clone, Serialize, TS)]
pub struct OperatorRunDetail {
    pub run: OperatorRun,
    pub provider_exchange: Option<crate::assessment::ProviderExchange>,
    pub execution_trace: Vec<ExecutionTraceEvent>,
}

/// Both checked-in browser bindings and contract tests use this single definition.
pub fn typescript() -> String {
    let config = ts_rs::Config::default();
    format!(
        "// Generated by cargo run --bin export-contracts --locked. Do not edit.\n{}\n",
        [
            CustomerMessage::decl(&config),
            AssessorId::decl(&config),
            AssessorOption::decl(&config),
            Intent::decl(&config),
            RunState::decl(&config),
            TaskState::decl(&config),
            ServicingTask::decl(&config),
            CustomerReply::decl(&config),
            ApiError::decl(&config),
            IntentSignal::decl(&config),
            ExecutionTraceEvent::decl(&config),
            crate::assessment::ProviderExchange::decl(&config),
            OperatorRun::decl(&config),
            OperatorRunDetail::decl(&config),
            crate::telemetry::LiveLog::decl(&config),
        ]
        .into_iter()
        .chain(crate::workflow::contracts::declarations(&config))
        .map(|declaration| format!("export {declaration}"))
        .collect::<Vec<_>>()
        .join("\n")
    )
}
